site_name: Programmation object - 420-2C3-MA - Hiver 2025
site_description: Site web du cours de programmation objet (420-2C3-MA) du Collège de Maisonneuve.
site_url: https://archambaultv-prof.github.io/2025H-420-2C3-MA/
nav:
  - Page d'acceuil: index.md
  - Échéancier: echeancier.md
  - Évaluations sommatives: evaluations.md
  - Semaine 1:
    - Plan de leçon: semaine_01/index.md
    - Les expressions: semaine_01/theorie/01_les_expressions.md
theme:
  name: material
  logo: assets/images/logo-white.svg
  favicon: assets/images/favicon.svg
  language: fr
  features:
    - content.code.copy
    - navigation.top
    - navigation.footer
repo_url: https://github.com/archambaultv-prof/2025H-420-2C3-MA
copyright: Le contenu de ce site est sous licence <a href="https://creativecommons.org/licenses/by/4.0/deed.fr">CC-BY 4.0</a>.
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list