site_name: Programmation object - 420-2C3-MA - Hiver 2025
site_description: Programmation object - 420-2C3-MA - Hiver 2025 - Collège de Maisonneuve.
site_url: https://archambaultv-prof.github.io/2025H-420-2C3-MA/
nav:
  - Page d'acceuil: index.md
  - Échéancier: echeancier.md
  - Évaluations sommatives: evaluations.md
  - Exercices: notes_exercices.md
  - Semaine 1:
    - Plan de leçon: semaine_01/index.md
    - Théorie:
      - Les expressions: semaine_01/theorie/01_expressions.md
      - Les structures conditionnelles: semaine_01/theorie/02_conditions.md
      - Les structures itératives: semaine_01/theorie/03_structures_iteratives.md
      - Les chaînes de caractères: semaine_01/theorie/04_chaines_caracteres.md
      - Les fonctions: semaine_01/theorie/05_fonctions.md
      - Les listes: semaine_01/theorie/06_listes.md
  - Semaine 2:
    - Plan de leçon: semaine_02/index.md
    - Théorie:
      - Introduction à NumPy: semaine_02/theorie/01_numpy_intro.md
      - Tableaux NumPy: semaine_02/theorie/02_ndarray.md
      - Statistiques avec NumPy: semaine_02/theorie/03_statistiques.md
  - Semaine 3:
    - Sommatif 1: semaine_03/sommatif_1.md
    - Plan de leçon: semaine_03/index.md
    - Théorie:
      - Programmation fonctionnelle: semaine_03/theorie/01_prog_func.md
      - Compréhensions de listes: semaine_03/theorie/02_list_comprehension.md
  - Semaine 4:
    - Plan de leçon: semaine_04/index.md
    - Théorie:
      - Les classes: semaine_04/theorie/01_classes.md
      - L'héritage: semaine_04/theorie/02_heritage.md
      - Réinventer les classes: semaine_04/theorie/03_reinventer_classes.md
  - Semaine 5:
    - Plan de leçon: semaine_05/index.md
    - Travail pratique 1: semaine_05/tp_1.md
  - Semaine 6:
    - Plan de leçon: semaine_06/index.md
    - Examen 1: semaine_06/examen_1.md
    - Théorie:
      - Classe abstraite: semaine_06/theorie/01_classe_abstraite.md
theme:
  name: material
  logo: assets/images/logo-white.svg
  favicon: assets/images/favicon.png
  language: fr
  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - navigation.top
    - navigation.footer
repo_url: https://github.com/archambaultv-prof/2025H-420-2C3-MA
copyright: Le contenu de ce site est sous licence <a href="https://creativecommons.org/licenses/by/4.0/deed.fr">CC-BY 4.0</a>.
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins: 
  # - social
  - search
